sudo: false
script: bash ./deploy.sh
env:
  global:
    - GH_REF: github.com/openactive/spec-template.git
    - secure: uMu0qW45VyEXLyrZRGVGoXpJ9gMSsoejg0YckoifZP7iKebFX78QiTt/XUcsaUKr4w2P6VMaVqDCbc8MXXF64aV9Hacbybm8DwVhH8RJEFbmYJRaCXBEPrR42ffzVASA9iqwTOq9wX98CWybJ5GcFZdMBXlWeKEIDz3zeEhzaglTM3MaQ8qXEx+tpNWtIAc1/jeBNerwqUImcOrmRimStVkpFB0h9B+4BITA8FOcxeMlTca1qD2ZRgGrKugYP2A1FNWHd2DpOs4PDLKnt6UbFW/Wh3xHc0fGPBrivj9iIOC9ytKkE6EF0LF7dEhnzCisgn6rSUVFhcu38PmDlOjgRsM8Myrpq+HgxCrXRYzT9vSzoRwg0OvJZlgEmpw3BRbaKy28A2ADjE1jko76ywj50cLNtwE4phS2x8IjsnFmixefIBwu+l3Z6YDwdEt9AYR2aNLXTHOugXOwtfOmYBRqXEgGq83D9CMQgc5U72PAw7HaGZeIoIPaS1iamfV3XKmpcAxmkEE+RUH5aI2zAHEQa+5Q3nu1ObVapAL064Wpcw6SBcdSFqYkhKO4MggGkt0bje2fmL/VDNr7zz5LFX3wesDGHTaRjAyr8pm1tcx1nrTJ8UO1VvOIDJ3IyNpTkgvyxYIQU3q+4g5KUsezi22hHMLz7hNxI/mCyDa3Yuctq3w=
