sudo: false
script: bash ./deploy.sh
env:
  global:
    - GH_REF: github.com/openactive/spec-template.git
    - secure: FksJT9qJSmZ0id3oFIYiLGflt8PUPPzRbVhEZQqYQtw9Aj7mhbRjvG+lbbHy1IfgYFtSb6FPM71gc93Z+6GzLi+W3FlpV2V8frN2B/g5g7QsMAgdBmIaBrRBsAppqIayS4whZ4qoy5qJIUO+wdX4lzQo/aUcOc3hTGsChner1ZzPn4wCsQXcIGzJNOUjxxfZoUftRIXjsSV1NQoAV51bav9pHN2oOZN0Yg8+OWD5lC1PjHEMDg+/Sxi2a3LGUqCh/6MunnSJN7LNaSgcAsXqksAFss2xtm1tY5dUgtDAnEnjfHKbbwOnmc6OnZXr8biJoAFAHnQSv5jzF5UEII5ts09hw96hP32kwrj7Q5mbQ0oUnA9nllRof3/RJxzQCglrrOrzQTzsGjTd/6A+kUk/p6Zy4Ur9kTGC8viHSqe1AmNQJbIZw7epBEFU1vfn30cgVif9FFhdMpDsUT8tZCnpmLPLLH1kyuduQT8TL9qSCKDLhnwdX1YJkjOmCBqB/ArKqFeuEG+xPZZd/jHzouGftj0OV5bZoqEMyF7p/j/R44nV98VO2RFsnSwkE9pp64om+E63fle0J2e80jFlnEDfWQoRKJ5gDd/eelBqBDgJpZY5KyEaHbvTEtlJX61ZUN7spN3ePhenG0WYUt8gov+jAIEN/LFtBOfck7UYtzR/YPU=
