sudo: false
script: bash ./deploy.sh
env:
  global:
    - GH_REF: github.com/openactive/spec-template.git
    - secure: xKE/kKA+OCkhXXxHelAZqAC+nmabXCEAzPTXutI0VzCjDS+XRhT5BTJ0FmLJLz0H+rOyvfxcbD05UNYkkE4wAWIUAeTkEpW56nfcswIaFP5fTA7xfgUY9Qwb/jGbt1TOfHfxZpwFVhar8cGYt4WI96eYpQ+5+oJHFvJ2KJq115hEtToFBm7EeMEb4CZf5NdVbVd66b+cLJjKh/nEzhhrmQ1Yx6HnguIuh5KHbZPIBEd5fpABcCOB2bS48SFUXKH4LpC4iLcqeWc2UepsUFvF9Xn0+dQCjfOzETR+XoUaL2SJ3V1Jr9d4GBZaRiTEYD6uNAgBdBktCeh5FsYPdZMHqoSULEoZKmXv//2wrdxieAW/l9KqeBHLe8/fIVaS+YiX9Tec+cIpgc9VFyCnNvyaB+rQDHERx6bVumoSv8lCcXIlFkopmMKz6rueMzkmjuVodupR9FGJG7u7JR971m1EENJpCnlP0X+DvEiwXiRN6mwgSBLIxxyNVcypMb0p9naEFv0Q267jxE8iMY6zGZcp3S/BWq7fQ5csY82HqQbuSt0a9gB8RoeNPFb0X0/66QcB9yRjjKGrMQZw0cxzeYgAF+ha9+MAsFRpfuAiwwrlpe9ftjRLBJOCYlFKn2pQ/vTGeN1bQ5AtzbtinxDiw0YsFYsLrqSdwaNd52eG8DB33V4=
