sudo: false
script: bash ./deploy.sh
env:
  global:
    - GH_REF: github.com/openactive/spec-template.git
    - secure: mzaFoSBGqp3WCLqT/IcNlb76aqVr4Iod6KC64hMHwzFlzd/MdKcVKOvOovPSece9Fqtizcjwo+fzTlzkj251W/REz9ZN/ASbGtiwLkDFjxLXSccdbvx8+kc5uKmm9FHXNVIPtrdlw9IK1MldqQMbjRASMU9QAt+snjuB/4qC1NdVRi/0au6an2XoYhR0TKAGEfNz1ZqjKqU0eipgp3gFeTurT99cohc82Tv4tl7sGpMJLUg2zqUtnuO/3B329OQFRVgLDVey6pzNGgA373CcghhMR+nk0gYjlVBpJLpTC4i++ugMgMvBslSM/zIOENATiK2uU4FnOWWFnkFbOBdWO2mmmKBTedxtfkdIpQQu863wlYVQwSghS9U6+GVcylutG6qjKwXyBMViS0RMFwVQJEaIsOK95Pj9WTVKxB/EvcyC8wMSbD2qCmYDpicNdL/6W9D14m8f9d+++6bvYFm7SR5UYPmTAF/4X8xFYaCwLXcH5VLC9uHHUgjGU62JcR47oOGP7QzsEbNZNHfJzuJljyt+8Qr1fQ4GnxLAj9g9h0UMKTlZbUfTuk9iUvyPhcg35I9BkmhK0+4xGiDY9RCQABPdQ2O9pEusxVkXxRPe7YisdKIaNFPaquKB5U0xsmRWh3i+yzHdYZnTK2N+MNLLrJwarNYkzK3IxG1krn9Qskc=
